version: '3.3'

services:
  db:
   image: mysql:latest
   volumes:
     - dbdata:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: SenhaSecreta
     MYSQL_DATABASE: wordpress
     MYSQL_USER: usuariowp
     MYSQL_PASSWORD: SenhaSecreta2

  wordpress:
   depends_on:
     - db
   image: wordpress:latest
   volumes:
     - wp-content:/var/www/html/wp-content
   ports:
     - "8000:80"
   restart: always
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: usuariowp
     WORDPRESS_DB_PASSWORD: SenhaSecreta2

volumes:
  dbdata:
  wp-content:

